eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
      web:
        exposure:
          include: "*"
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s












spring:
  datasource:
    url: jdbc:postgresql://localhost:33008/task_db
    username: my_user
    password: my_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ream-mini-project
          jwk-set-uri: http://localhost:8080/auth/realms/ream-mini-project/protocol/openid-connect/certs
  application:
    name: task-service


server:
  port: 8282


openapi:
  service:
    title: task-service #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:9001 #api gateway url
  oAuthFlow:
    tokenUrl: http://localhost:8080/auth/realms/ream-mini-project/protocol/openid-connect/token


springdoc:
  api-docs:
    path: /task-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /task-service/swagger-ui.html