spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ream-mini-project
          jwk-set-uri: http://localhost:8080/auth/realms/ream-mini-project/protocol/openid-connect/certs
  application:
    name: keycloak-client
server:
  port: 8181
keycloak:
  realm: ream-mini-project
  resource: spring-microservice-mini-project
  auth-server-url: http://localhost:8080/auth/ #docker container

  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'spring-microservice-mini-project'
    secret: 'V7uwI888k5hlKDiVwKIAnqU2EhjM9MY1'
    provider: secret
logging:
  level:
    org.springframework.web: debug


openapi:
  service:
    title: keycloak-client #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:9001 #api gateway url
  oAuthFlow:
    tokenUrl: http://localhost:8080/auth/realms/ream-mini-project/protocol/openid-connect/token


springdoc:
  api-docs:
    path: /keycloak-client/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /keycloak-client/swagger-ui.html